### ISSUE TITLE
Is there a way to change the structure?

### ISSUE THREAD

**Issue by vanhoutenbos** [kytmanov/postmanBackup#1]
We would like to have a different structure because we use GIT as our sourcing system.
Is it possible to change the structure so that the /[postman-id]/[date]/ is gone?
We would just like
/collections/*.json
/enviroments/*.json

**Comment by kytmanov** [comment]
Absolutely. You need to go to **config.json** and set  
**"use_date_subfolder": false**
**"use_id_subfolder": false**

**Comment by vanhoutenbos** [comment]
Thank you! This worked like a charm!
